# Generated by Django 3.1.7 on 2021-03-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20210313_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveBigIntegerField(null=True)),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='rooms.room')),
            ],
        ),
    ]
