# Generated by Django 3.1.7 on 2021-03-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('room', models.ManyToManyField(to='rooms.Room')),
            ],
        ),
    ]
