# Generated by Django 3.1.7 on 2021-03-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='properties',
            field=models.ManyToManyField(null=True, to='rooms.Property'),
        ),
    ]
